version: '3.8'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python bot.py
