# Используем базовый образ Python
FROM python:3.11

# Устанавливаем рабочий каталог
WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота в контейнер
COPY . .

# Определяем команду, которая будет выполнена при запуске контейнера
CMD ["python", "bot.py"]
